### ISSUE TITLE
query search result - array count mismatch

### ISSUE THREAD

**Issue by fgaebel** [dersam/RTPHPLib#30]
Hi, 

it seems that the $responseArray returned by the $rt->search function has one "empty" item to much in it. My guess is that there is no longer a prefaced multiline with a single space as commented in the *parseResponse* function?

![2015-10-02 19_47_21-info-center](https://cloud.githubusercontent.com/assets/12672520/10253660/d76218a6-693e-11e5-86d5-d0b6fb34217f.gif)

**Comment by dersam** [comment]
What version of rt was this on?

**Comment by fgaebel** [comment]
I used Version 4.2.12. 
Exploding the response with chr(10) in *parseResponse* leads to the extra element in the array.

**Comment by ParisLiakos** [comment]
I see this with all methods, not just search..All response arrays have an extra item, empty key and empty value..
probably because RT returns 2 extra new lines in the end of the response

**Comment by dersam** [comment]
Resolved by #34

**Comment by ParisLiakos** [comment]
Not resolved, i still see it with both rt 4.0 and 4.2

**Comment by dersam** [comment]
My bad, reopening. Wildly misread that merge.
