### ISSUE TITLE
Attachment handling on ticket creation

### ISSUE THREAD

**Issue by drdreidel101** [dersam/RTPHPLib#53]
Provide a way to add attachments to the content array when creating tickets.

**Comment by dersam** [comment]
@Leusev @ParisLiakos Is this currently possible?

**Comment by ParisLiakos** [comment]
There is no such possibility in API level. You cant attach files on ticket creation.
Maybe with the new REST API...

**Comment by Gela** [comment]
Is there a way to get the Id of the most recently created ticket right after it's creation to post attachments as a reply?

We have a snippet of code that saves all the attachments into an array in the same php file that initializes and creates the ticket so ideally we want to post the reply with attachments at the same time.

**Comment by dersam** [comment]
The response for ticket creation should contain the ticket id.  Check out the unit tests for an example of how to pull out the ticket id.  [Example](https://github.com/dersam/RTPHPLib/blob/master/tests/RequestTrackerTest.php#L47)

**Comment by Gela** [comment]
Thanks for the help. I copied the following function over:

```php
private function getTicketIdFromCreateResponse($resp)
    {
        $matches = array();
        preg_match(
            '/^# Ticket\b (\d+)\b created\.$/',
            key($resp),
            $matches
        );
        return array_pop($matches);
    }
```

and in the php file where we're creating the ticket, I did the following:

```php
$response = $rt->createTicket($ticket);
$ticketId = $this->getTicketIdFromCreateResponse($response);
var_dump($ticketId);
```

but $ticketId is empty and var_dump does not print anything. Am I doing something wrong?

**Comment by dersam** [comment]
What does var_dump($response) look like before you call getTicketId()?

**Comment by drdreidel101** [comment]
Hi Dersam. I ran into the same issue as Gela (we are working on this project together). I was able to extract the ticketID into a string doing this:

```php
/*create ticket */
$response = $rt->createTicket($ticket);

/*turn response into a string */
$response = implode(array_keys($response));

/*extract ticket id from string */
$ticketID = preg_replace("/[^0-9]/","",$response);
```

**Comment by ParisLiakos** [comment]
Imploding all response lines is not probably not bulletproof ;)
If RT API decides to add an integer in its response, at any line, your id will be scrambled and invalid.

I am using a similar way like in the tests to extract the ID.

`if (preg_match('/\# Ticket (\d+) created\./', $message, $matches)) {
  $id = $matches[1];
}`

It would be nice to make createTicket() return the id actually..i ll create a pull request for that

**Comment by ParisLiakos** [comment]
@drdreidel101 whats the RT version you use? The above is tested against RT 4.2.12

**Comment by drdreidel101** [comment]
@ParisLiakos Thanks for the tip. That preg_match is definitely tighter, Now that I've got the ticketId on creation I just need to figure out how to comment attachments right after.

**Comment by drdreidel101** [comment]
@ParisLiakos My version of RT is 4.0.7

**Comment by ParisLiakos** [comment]
Hmm, weird 4.0.7 has the same message as far as i can see with 4.2.12
https://github.com/bestpractical/rt/blob/rt-4.0.7/share/html/REST/1.0/Forms/ticket/default#L204

So, what i think is wrong with the code in https://github.com/dersam/RTPHPLib/issues/53#issuecomment-188863671 , is that
`key($resp)`
is a blank line instead of the line with the actual success message.

**Comment by drdreidel101** [comment]
@dersam Would it be possible to update example.php with some code detailing how to add attachments to a ticket via a comment?

**Comment by Gela** [comment]
@dersam @ParisLiakos Any pointers on how to send an attachment as a comment would be greatly appreciated. Below is the function we've been using to add comments, and we are at loss as to why the attachments do not go through.

```php
    public function doTicketComment($ticketId, $content)
    {
        $content['Action'] = 'comment';
        $url = $this->url."ticket/$ticketId/comment";

        if (isset($content['Text'])) {
            $content['Text'] = str_replace("\n", "\n ", $content['Text']);
        }

        $this->setRequestUrl($url);
        $this->setPostFields($content);

        // If we have attachment_1 content, we have to pass it apart from inside 'content' array position
        // and unset from postFields and from 'content' array because cannot convert CurlObject to String
        // into parseArray() method inside send()
        if ( ! empty($content['attachment_1'] ) ) {
            $attachContent = array();            
            // search for all file fields            
            $i = 1;
            foreach($content as $key => $value){
                if( strncmp($key, "attachment_", 11) == 0 ) {
                    $attachContent[$i] = $value;
                    unset($content['attachment_'.$i]);
                    unset($this->postFields['attachment_'.$i]);
                    $i++;
                }
            }
            $response = $this->send(false, $attachContent);
			print_r($response);

        } else {
            $response = $this->send();
			print_r($response);
        }
        return $this->parseResponse($response);
		print_r($response);
    }
```

**Comment by ParisLiakos** [comment]
@Gela I am not sure, but if you use the dev-master version, you will find some code and documentation improvements i have made. Thats the version i am using and it works for me.

**Comment by dersam** [comment]
@Gela My bad, I never made an official release with the fixes @ParisLiakos made. Try version 1.2.3 if you're not comfortable with defining a composer dependency on a non-release, it's equivalent to master now.

**Comment by dersam** [comment]
@ParisLiakos When you get a chance, can you add a usage example to example.php for attachments?

**Comment by oijkn** [comment]
@dersam Hi, i would like to thanks you for this great LIB, that made me save much time ! I can create/edit/reply using your functions but i don't really understand how to attach multiple files when i reply to a ticket... Can you (or anyone else) provide me an example please ?

Thank you in advance, regards.

**Comment by ParisLiakos** [comment]
I use something like this on PHP 7:
`
$attachments = [];
if ($request->hasFile('attachments')) {
    foreach ($request->file('attachments') as $file) {
        if ($file->isValid() && !$file->isLink()) {
            $attachments[$file->getClientOriginalName()] = new \CURLFile($file->getRealPath(),$file->getMimeType(), $file->getClientOriginalName());
        }
    }
}

$edit = [
    'Text' => $request->input('text'),
    'Content-Type' => 'text/html',
];
$this->rtClient->doTicketReply($id, $data, $attachments);
`

This should only work for PHP > 5.5
If you  run lower, then check the documentation for [RequestTracker::send()](https://github.com/dersam/RTPHPLib/blob/master/RequestTracker.php#L101)

**Comment by Gela** [comment]
Here's another solution. Basically we email the attachments to RT and from there RT adds them to the ticket. We are also using phpMailer (https://github.com/PHPMailer/PHPMailer) to send the email. We have a tmp directory where we're 'hosting' the file, but we don't need it once it goes through and is on RT so we have another snippet of code and cleans the directory every time.

```php
/* Multiple Attachment code */
	if(isset($_FILES['UploadFileField'])){
        //Loop through each file
        for($i=0; $i<count($_FILES['UploadFileField']['name']); $i++) {
			
          //Get the temp file path
            $UploadTmp[$i] = $_FILES['UploadFileField']['tmp_name'][$i];
			$UploadType[$i] = $_FILES['UploadFileField']['type'][$i];
			$FileSize[$i] = $_FILES['UploadFileField']['size'][$i];
            
            //save the filename
            $UploadName[$i] = $_FILES['UploadFileField']['name'][$i];
				
			if(($FileSize[$i] > 419430400)){
				die("Error - File too Big");
			}
			else{
                //Upload the file into the  temp dir
				//'/tmp/$UploadName[$i]'
               	move_uploaded_file($UploadTmp[$i], "$uploads_path/$UploadName[$i]");
				$file_to_attach = "$uploads_path/$UploadName[$i]";
				$phpMailer->AddAttachment( utf8_decode($file_to_attach) , utf8_decode($UploadName[$i]) );
				
			}
    	}
	}
/* End of multiple attachment code */
```

**Comment by oijkn** [comment]
@ParisLiakos @dersam Thank you for your quick reply and for the snippet code ! I will try to investigate and adapt it to my project !

Meanwhile, is it possible to have a concrete example based on the source RTPHPLIB, please ?

`$url = "http://rt.easter-eggs.org/demos/4.2/";
$user = "admin";
$pass = "admin";

$rt = new RequestTracker($url, $user, $pass);

$attachments = []; // i don't know what to do with that ???

$content = array(
    'Text'=>'This is a test reply.',
    'Attachment'=>'uploadTest'
);
$response = $rt->doTicketReply(233, $content, $attachments);
print_r($response);`

@Gela Thanks you too for your help, but in my case i must use RT to reply & attach file. I can't use third "addon" to make the job.

By the way thank you all for helping me in this pain.

Best regards.

**Comment by oijkn** [comment]
@ParisLiakos I want to thanks you very much for helping me in this !! You make my day mate :) and thank you for your great contribution !!

Best regards.

PS: i replied you in your other post with my little issue ==> https://github.com/dersam/RTPHPLib/pull/57#issuecomment-203966400

**Comment by dersam** [comment]
Closing - @ParisLiakos 's example code has been merged.
