### ISSUE TITLE
add "fields" parameter to search function

### ISSUE THREAD

**Issue by dillonsavage** [dersam/RTPHPLib#70]
I'm interested in specifying fields to return from, e.g., a ticket search (not just ticket id/title). I think it could be done pretty easily by just adding a parameter to the search function. I notice that there's already an open issue about that but it seems specifically to be about pagination, which might be more complicated. Thanks!

**Comment by petski** [comment]
Seems to be fixed in https://github.com/dersam/RTPHPLib/commit/04d5827e05edbf5e26331714756e42cfc0e56e6c (and already part of latest version, which is 1.4.0)

**Comment by dersam** [comment]
Correct, @dillonsavage's patch for this was merged in #71, and released in 1.4.0.
