### ISSUE TITLE
SearchTickets issue with Subject (or any other field) containing "id: "

### ISSUE THREAD

**Issue by petski** [dersam/RTPHPLib#72]
If the Subject field contains something like `Request for user id: 123`, the parsing in `parseLongFormatSearchResponse()` goes wrong. This is caused by the fact that the subjectline contains `id: `.

Please cherry-pick https://github.com/petski/RTPHPLib/commit/a60db5fe213920c6b57e3fc4726f5e62a88de3ae to resolve this issue

**Comment by petski** [comment]
Please?

**Comment by dersam** [comment]
Please submit this as a pull request. I don't have time to cherry pick commits for changes, and cherry-picking skips the automated testing I have in place.
